AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sample template to deliver events from Amazon EventBridge to CloudWatch Logs

Resources:
  StateMachineLogs:
    Type: AWS::Logs::LogGroup

  StateMachineForWeatherData:
    Type: AWS::Serverless::StateMachine
    Properties:
      # Logging is a good idea. We also need at least one policy attached to the Step
      # Function in order to deploy.
      Logging:
        Level: ERROR
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt StateMachineLogs.Arn
      Policies:
        - Statement:
          - Effect: Allow
            Action:
              - logs:*
            Resource: "*"
      DefinitionUri: statemachine/workflow.asl.json
      Events:
        StateChange:
          Type: EventBridgeRule
          Properties:
            EventBusName: default
            # The detail key contains the EC2 specific event data. In this example, the
            # rest of the event properties are not needed and discarded.
            InputPath: $.detail
            Pattern:
              source:
                - demo.event

  LogsRule:
    Type: AWS::Events::Rule
    Properties:
      EventBusName: default
      EventPattern:
        source: 
          - 'demo.event'
        account:
          - !Ref AWS::AccountId
      Targets:
        - Arn: !GetAtt LogGroupForEvents.Arn
          Id: LogTarget
  LogGroupForEvents:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/events/state-machine-test
  LogGroupForEventsPolicy:
    Type: AWS::Logs::ResourcePolicy
    Properties:
      PolicyName: EventBridgeToCWLogsPolicy
      PolicyDocument: !Sub >
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Sid": "EventBridgetoCWLogsCreateLogStreamPolicy",
              "Effect": "Allow",
              "Principal": {
                "Service": [
                  "events.amazonaws.com"
                ]
              },
              "Action": [
                "logs:CreateLogStream"
              ],
              "Resource": [
                "${LogGroupForEvents.Arn}"
              ]
            },
            {
              "Sid": "EventBridgetoCWLogsPutLogEventsPolicy",
              "Effect": "Allow",
              "Principal": {
                "Service": [
                  "events.amazonaws.com"
                ]
              },
              "Action": [
                "logs:PutLogEvents"
              ],
              "Resource": [
                "${LogGroupForEvents.Arn}"
              ],
              "Condition": {
                "ArnEquals": {"AWS:SourceArn": "${LogsRule.Arn}"}
              }
            }
          ]
        }